// src/components/block/BlockElementExists.vue
<template>
  <block-base
    :id="componentId"
    class="element-exists"
    style="width: 195px"
    @edit="editBlock"
    @delete="$emit('delete', id)"
  >
    <Handle :id="`${id}-input-1`" type="target" :position="Position.Left" />
    <div
      :class="data.disableBlock ? 'bg-box-transparent' : block.category.color"
      class="inline-block text-sm mb-2 p-2 rounded-lg dark:text-black"
    >
      <v-remixicon name="riFocus3Line" size="20" class="inline-block mr-1" />
      <span>{{ t('workflow.blocks.element-exists.name') }}</span>
    </div>
    <p
      :title="t('workflow.blocks.element-exists.selector')"
      :class="{ 'font-mono': !data.description }"
      class="text-overflow p-2 rounded-lg bg-box-transparent text-sm text-right mb-2"
      style="max-width: 200px"
    >
      {{
        data.description ||
        data.selector ||
        t('workflow.blocks.element-exists.selector')
      }}
    </p>
    <p class="text-right text-gray-600 dark:text-gray-200">
      <span :title="t('workflow.blocks.element-exists.fallbackTitle')">
        &#9432;
      </span>
      {{ t('common.fallback') }}
    </p>
    <Handle :id="`${id}-output-1`" type="source" :position="Position.Right" />
    <Handle
      :id="`${id}-output-2`"
      type="source"
      :position="Position.Right"
      style="top: auto; bottom: 12px"
    />
  </block-base>
</template>
<script setup>
import { useI18n } from 'vue-i18n';
import { Handle, Position } from '@braks/vue-flow';
import emitter from '@/lib/mitt';
import { useComponentId } from '@/composable/componentId';
import { useEditorBlock } from '@/composable/editorBlock';
import BlockBase from './BlockBase.vue';

const props = defineProps({
  id: {
    type: String,
    default: '',
  },
  label: {
    type: String,
    default: '',
  },
  data: {
    type: Object,
    default: () => ({}),
  },
});
defineEmits(['delete']);

const { t } = useI18n();
const block = useEditorBlock(props.label);
const componentId = useComponentId('block-delay');

function editBlock() {
  emitter.emit('editor:edit-block', {
    ...block.details,
    data: props.data,
    blockId: block.id,
  });
}
</script>
<style>
.drawflow .element-exists .outputs {
  top: 70px !important;
  transform: none !important;
}
.drawflow .element-exists .output {
  margin-bottom: 22px;
}
</style>

// src/components/block/BlockElementExists.tsx
import React, { useMemo } from 'react';
import { Handle, Position, NodeProps } from 'reactflow';
import BlockBase, { BlockBaseProps, RemixIcon } from './BlockBase';

// Define structure for block definition data BlockElementExists expects
interface BlockElementExistsDefinition {
  id: string; // e.g., 'element-exists'
  name: string; // Default name "Element Exists"
  icon?: string;
  category?: { color?: string };
}

// Define data structure for BlockElementExists node
export interface BlockElementExistsData {
  description?: string;
  selector?: string;
  disableBlock?: boolean;
  $breakpoint?: boolean;

  blockDefinition?: BlockElementExistsDefinition;

  // Callbacks
  onUpdateData?: (updatedData: Partial<BlockElementExistsData>) => void;
  onDelete?: () => void;
  onSettings?: () => void;
  onEdit?: () => void;
}

const BlockElementExists: React.FC<NodeProps<BlockElementExistsData>> = ({ id: instanceId, data, selected, type }) => {
  const {
    description,
    selector,
    disableBlock,
    $breakpoint,
    blockDefinition,
    onUpdateData,
    onDelete,
    onSettings,
    onEdit,
  } = data;

  const t = (key: string, defaultVal?: string) => defaultVal || key; // Placeholder i18n

  const definition = useMemo<BlockElementExistsDefinition>(() => blockDefinition || {
    id: type,
    name: 'Element Exists',
    category: { color: 'bg-teal-200' }, // Example color
    icon: 'riFocus3Line',
  }, [blockDefinition, type]);

  const blockName = t('workflow.blocks.element-exists.name', definition.name);
  const iconColor = disableBlock ? 'bg-gray-300 dark:bg-gray-600' : definition.category?.color || 'bg-teal-500';

  const displaySelector = description || selector || t('workflow.blocks.element-exists.selector', 'CSS Selector');

  const blockBaseProps: BlockBaseProps = {
    blockId: instanceId,
    data: { disableBlock, $breakpoint, ...data },
    blockData: { details: { id: definition.id, name: blockName, icon: definition.icon } },
    onDelete,
    onEdit: onEdit || onSettings,
    onSettings,
    onUpdate: onUpdateData,
    selected,
    contentClass: 'p-2', // Custom padding
  };

  // Approximate handle positions from Vue version; top output is default, second is lower.
  // In React Flow, `Handle` positions are relative to the node bounds.
  // The `style` prop on `Handle` can be used for fine-tuning.
  // The Vue `style="top: auto; bottom: 12px"` for the second handle is relative to its parent.
  // We'll position the first handle normally (React Flow centers it vertically by default on L/R).
  // The second handle will be explicitly positioned lower.

  return (
    <BlockBase {...blockBaseProps} className="block-element-exists w-52"> {/* Width from Vue: 195px, adjusted */}
      <Handle type="target" position={Position.Left} id={`${instanceId}-input-1`} style={{ background: '#555' }} />

      <div className={`mb-1 inline-flex items-center rounded-lg p-1.5 text-xs dark:text-black ${iconColor}`}>
        <RemixIcon name={definition.icon || 'riFocus3Line'} size="18" className="mr-1" />
        <span>{blockName}</span>
      </div>

      <p
        title={t('workflow.blocks.element-exists.selector', 'CSS Selector')}
        className={`text-overflow bg-gray-50 dark:bg-gray-700/50 mb-1 rounded-md p-1.5 text-xs text-right truncate ${!description ? 'font-mono' : ''}`}
      >
        {displaySelector}
      </p>

      {/* Text for the second output handle (Fallback) */}
      <div className="text-right text-xs text-gray-500 dark:text-gray-400 pr-1">
        <span title={t('workflow.blocks.element-exists.fallbackTitle', 'Element does not exist') || 'Element does not exist'}>
          ℹ
        </span>
        {' '}{t('common.fallback', 'Fallback')}
      </div>

      {/* Output handle 1 (True / Element exists) */}
      {/* React Flow positions this mid-right by default. If more specific position needed, use style.top */}
      <Handle
        type="source"
        position={Position.Right}
        id={`${instanceId}-output-1`}
        style={{ background: '#555', top: '35%' }} // Adjusted for two outputs
      />

      {/* Output handle 2 (False / Fallback) */}
      <Handle
        type="source"
        position={Position.Right}
        id={`${instanceId}-output-2`}
        style={{ background: '#555', top: '65%' }} // Positioned lower
      />
    </BlockBase>
  );
};

export default BlockElementExists;
